// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "dba8dd65a913451a1af8a0356076b372"
    },
    {
        "url": "icon-96.png",
        "revision": "713aa68406b597d63ec5604bbb655a14"
    },
    {
        "url": "icon-128.png",
        "revision": "184b7cd0f04ee5d52114ce392f053866"
    },
    {
        "url": "icon-144.png",
        "revision": "d9ba7f94184442a4f172bbf35ca26040"
    },
    {
        "url": "icon-152.png",
        "revision": "4a0c583db89f1c4470ca924d2bbd3c3c"
    },
    {
        "url": "icon-192.png",
        "revision": "a9cc0f574993097021168c338da48ef9"
    },
    {
        "url": "icon-384.png",
        "revision": "0f72418492b4beee2c69e31435f2906c"
    },
    {
        "url": "icon-512.png",
        "revision": "dc06795bc4b106966b2e19e275dca1d2"
    },
    {
        "url": "favicon.ico",
        "revision": "13c155d1410bcdd7ec2739a5e115669f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "audit_report_urdu.md",
        "revision": "2e7a98bffc16ac5ee32885f8d991c33e"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "08c0ac9ca1b42370924c8a12997f7cfd"
    },
    {
        "url": "capture_modal_1770923756261.webp",
        "revision": "6003354ce1b1a9b10d63f03a01cd99f1"
    },
    {
        "url": "Copy (2) of index.html",
        "revision": "fc30db0ebd03f46694da3d18b59e00bd"
    },
    {
        "url": "Copy of index.html",
        "revision": "62c7f284ced45c996f9cd3bcd1bbfff0"
    },
    {
        "url": "dashboard_view.png",
        "revision": "d66a9a8986dfa2cb7836a6890226fba0"
    },
    {
        "url": "icon.svg",
        "revision": "93c79b3b36f7d75297b1ee791361a228"
    },
    {
        "url": "index.html",
        "revision": "afd2149356cdb9e400a9b6011cc81aea"
    },
    {
        "url": "logo.png",
        "revision": "c9ad0334ab935e09260561c96c83c92b"
    },
    {
        "url": "logo2.png",
        "revision": "c6587801f55c555866166a21a32987c4"
    },
    {
        "url": "manifest.json",
        "revision": "cb2ffe203d2230b4c91b97f77ad918eb"
    },
    {
        "url": "modal_view.png",
        "revision": "152599251da2d85d8c345b44f4f937e9"
    },
    {
        "url": "offline.html",
        "revision": "8987c4b748db7cbdf5e4c6165507121b"
    },
    {
        "url": "Ramadan_Tracker_2026-02-12 (1).png",
        "revision": "f9165ec181106b759ec009a75d7327e8"
    },
    {
        "url": "readme.md",
        "revision": "caa229629c49f522702510555baf69c3"
    },
    {
        "url": "sw.js",
        "revision": "20bd8038b5a2af17fd6ab2e3a7a6dc74"
    },
    {
        "url": "lib/.gitkeep",
        "revision": "d41d8cd98f00b204e9800998ecf8427e"
    },
    {
        "url": "lib/confetti.js",
        "revision": "e3b4c83cb818e4994c82d97300316db8"
    },
    {
        "url": "lib/html2canvas.js",
        "revision": "d7530aa0b7587e627484c49fdf8f13f2"
    },
    {
        "url": "lib/tailwindcss.js",
        "revision": "7a614b9a197e532c00d09a23b0996b5f"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}